grafana:
  image: bitnami/grafana:latest
  restart: unless-stopped
  ports:
    - "3000:3000"
  environment:
    - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community"
    - "GF_INSTALL_PLUGINS=meln5674-mongodb-community=${ZIP_URL}"
